Resolve undefined method error with eager loading enabled
Because:

The following error happened when deploying to staging, which had
`config.eager_load = true`, but which didn't happen in local
development:

```
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.1.0/lib/rails/application/finisher.rb:134:in `each': undefined method `eager_load!' for Hotwire:Module (NoMethodError)
from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.1.0/lib/rails/application/finisher.rb:134:in `block in <module:Finisher>'
```

Solution:

* Extend `ActiveSupport::Autoload`, like the `turbo-rails` gem does
* This provides the `eager_load!` method